# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "~> 5.26"
    }
  }
}

provider "aws" {
  region = "ap-northeast-1"
  profile = "fw"
}
